import Link from "next/link";
import { ArrowLeft, Save } from "lucide-react";
import { notFound } from "next/navigation";
import { getWeddingContext } from "@/lib/wedding";
import { updateGuest } from "../actions";

export default async function GuestDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}){
  const {id}=await params;const p=await searchParams;const {supabase,wedding}=await getWeddingContext();if(!wedding)return null;
  const [{data:g,error},{data:households},{data:meals},{data:assignment}]=await Promise.all([supabase.from("guests").select("*").eq("id",id).eq("wedding_id",wedding.id).maybeSingle(),supabase.from("households").select("id,household_name").eq("wedding_id",wedding.id).order("household_name"),supabase.from("meal_options").select("id,name").eq("wedding_id",wedding.id).eq("is_active",true).order("sort_order"),supabase.from("guest_table_assignments").select("tables(name),seats(seat_number)").eq("guest_id",id).maybeSingle()]);
  if(error||!g)notFound();const action=updateGuest.bind(null,id);
  return <div className="page guest-detail"><Link className="back-link" href="/guests"><ArrowLeft/>Back to guests</Link><div className="page-header"><div><p className="eyebrow">Guest record</p><h1>{g.preferred_name||g.first_name} {g.last_name}</h1><p className="muted dashboard-intro">Keep invitation, RSVP and practical requirements together.</p></div><span className={`badge ${g.rsvp_status==="attending"?"badge-success":g.rsvp_status==="declined"?"badge-danger":"badge-waiting"}`}>{g.rsvp_status}</span></div>{p.error&&<div className="alert alert-error">{p.error}</div>}<form action={action} className="detail-layout"><div className="detail-main">
    <Section title="Identity & invitation"><div className="form-grid"><Field label="First name" name="first_name" value={g.first_name} required/><Field label="Last name" name="last_name" value={g.last_name}/><Field label="Preferred name" name="preferred_name" value={g.preferred_name}/><Select label="Household" name="household_id" value={g.household_id} options={[["","No household"] as [string,string],...(households||[]).map(h=>[h.id,h.household_name] as [string,string])]}/><Select label="Guest type" name="guest_type" value={g.guest_type} options={[["day","Day guest"],["evening","Evening guest"],["ceremony_only","Ceremony only"],["supplier","Supplier"]]}/><Select label="Age group" name="age_group" value={g.age_group} options={[["adult","Adult"],["child","Child"],["baby","Baby"]]}/></div></Section>
    <Section title="Contact details"><div className="form-grid"><Field label="Email" name="email" value={g.email} type="email"/><Field label="Telephone" name="telephone" value={g.phone} type="tel"/></div></Section>
    <Section title="RSVP & meal"><div className="form-grid"><Select label="RSVP status" name="rsvp_status" value={g.rsvp_status} options={[["awaiting","Awaiting response"],["attending","Attending"],["declined","Declined"]]}/><Select label="Meal selection" name="meal_option_id" value={g.meal_option_id} options={[["","No meal selected"] as [string,string],...(meals||[]).map(m=>[m.id,m.name] as [string,string])]}/><div className="field span-2"><label htmlFor="dietary_requirements">Dietary requirements</label><textarea className="textarea" id="dietary_requirements" name="dietary_requirements" defaultValue={g.dietary_requirements||""}/></div><Field label="Allergies" name="allergies" value={g.allergies}/><Field label="Accessibility requirements" name="accessibility_requirements" value={g.accessibility_requirements}/></div></Section>
    <Section title="Practical details"><div className="form-grid"><label className="check-label"><input type="checkbox" name="plus_one_allowed" defaultChecked={g.plus_one_allowed}/> Plus-one allowed</label><Field label="Plus-one name" name="plus_one_name" value={g.plus_one_name}/><label className="check-label"><input type="checkbox" name="accommodation_required" defaultChecked={g.requires_accommodation}/> Accommodation required</label><Field label="Accommodation details" name="accommodation_details" value={g.accommodation_notes}/><label className="check-label"><input type="checkbox" name="transport_required" defaultChecked={g.requires_transport}/> Transport required</label><Field label="Seat number" name="seat_number" value={g.seat_number} type="number"/></div></Section>
    <Section title="Notes"><div className="field"><label htmlFor="private_notes">Private notes</label><textarea className="textarea tall" id="private_notes" name="private_notes" defaultValue={g.private_notes||""}/></div></Section></div>
    <aside className="detail-side"><div className="card card-pad"><h3>Communication</h3><div className="stack-fields"><Select label="Invitation" name="invitation_status" value={g.invitation_status} options={[["not_sent","Not sent"],["sent","Sent"],["delivered","Delivered"],["returned","Returned"]]}/></div></div><div className="card card-pad"><h3>Seating</h3><p className="muted small">{assignment?(assignment.tables as unknown as {name:string})?.name||"Assigned":"Not assigned"}</p><p className="small">Use the table planner in Phase 2 for drag-and-drop assignments.</p></div><div className="card card-pad"><h3>After the wedding</h3><div className="stack-fields"><label className="check-label"><input type="checkbox" name="gift_received" defaultChecked={g.gift_received}/> Gift received</label><label className="check-label"><input type="checkbox" name="thank_you_sent" defaultChecked={g.thank_you_sent}/> Thank-you card sent</label></div></div><button className="button button-primary save-button" type="submit"><Save/>Save guest</button></aside>
  </form></div>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="card detail-section"><div className="detail-section-title"><h2>{title}</h2></div><div className="detail-section-body">{children}</div></section>}
function Field({label,name,value,type="text",required=false}:{label:string;name:string;value:unknown;type?:string;required?:boolean}){return <div className="field"><label htmlFor={name}>{label}</label><input className="input" id={name} name={name} type={type} defaultValue={String(value??"")} required={required}/></div>}
function Select({label,name,value,options}:{label:string;name:string;value:unknown;options:[string,string][]}){return <div className="field"><label htmlFor={name}>{label}</label><select className="select" id={name} name={name} defaultValue={String(value??"")}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>}
