"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getWeddingContext } from "@/lib/wedding";

const val=(form:FormData,key:string)=>String(form.get(key)||"").trim();const nullable=(form:FormData,key:string)=>val(form,key)||null;
function taskPayload(form:FormData){const status=val(form,"status")||"not_started";return{title:val(form,"title"),description:nullable(form,"description"),category:nullable(form,"category"),priority:val(form,"priority")||"medium",status,assigned_user_id:nullable(form,"assigned_user_id"),due_date:nullable(form,"due_date"),completed_at:status==="completed"?new Date().toISOString():null,supplier_id:nullable(form,"supplier_id"),guest_id:nullable(form,"guest_id"),budget_item_id:nullable(form,"budget_item_id"),timeline_item_id:nullable(form,"timeline_item_id")};}
export async function addTask(formData:FormData){const{supabase,wedding,user}=await getWeddingContext();if(!wedding)redirect("/dashboard");const{data,error}=await supabase.from("tasks").insert({wedding_id:wedding.id,created_by:user.id,...taskPayload(formData)}).select("id").single();if(error)redirect(`/tasks?error=${encodeURIComponent(error.message)}`);await supabase.from("activity_log").insert({wedding_id:wedding.id,action:"task_added",entity_type:"task",entity_id:data.id,description:`Task added: ${val(formData,"title")}`});revalidatePath("/tasks");revalidatePath("/dashboard");redirect("/tasks?message=Task added");}
export async function updateTask(id:string,formData:FormData){const{supabase,wedding}=await getWeddingContext();if(!wedding)redirect("/dashboard");const payload=taskPayload(formData);const{error}=await supabase.from("tasks").update(payload).eq("id",id).eq("wedding_id",wedding.id);if(error)redirect(`/tasks?error=${encodeURIComponent(error.message)}`);if(payload.status==="completed")await supabase.from("activity_log").insert({wedding_id:wedding.id,action:"task_completed",entity_type:"task",entity_id:id,description:`Task completed: ${payload.title}`});revalidatePath("/tasks");revalidatePath("/dashboard");redirect("/tasks?message=Task updated");}
export async function setTaskStatus(id:string,status:string){const{supabase,wedding}=await getWeddingContext();if(!wedding)throw new Error("Wedding workspace not found.");const{error}=await supabase.from("tasks").update({status,completed_at:status==="completed"?new Date().toISOString():null}).eq("id",id).eq("wedding_id",wedding.id);if(error)throw new Error(error.message);if(status==="completed")await supabase.from("activity_log").insert({wedding_id:wedding.id,action:"task_completed",entity_type:"task",entity_id:id,description:"Task marked complete"});revalidatePath("/tasks");revalidatePath("/dashboard");}
export async function deleteTask(id:string){const{supabase,wedding}=await getWeddingContext();if(!wedding)redirect("/dashboard");const{error}=await supabase.from("tasks").delete().eq("id",id).eq("wedding_id",wedding.id);if(error)redirect(`/tasks?error=${encodeURIComponent(error.message)}`);revalidatePath("/tasks");revalidatePath("/dashboard");}
export async function addChecklistItem(taskId:string,formData:FormData){const{supabase,wedding}=await getWeddingContext();if(!wedding)redirect("/dashboard");const{error}=await supabase.from("task_checklist_items").insert({wedding_id:wedding.id,task_id:taskId,title:val(formData,"checklist_title")});if(error)redirect(`/tasks?error=${encodeURIComponent(error.message)}`);revalidatePath("/tasks");}
export async function toggleChecklistItem(id:string,complete:boolean){const{supabase,wedding}=await getWeddingContext();if(!wedding)throw new Error("Wedding workspace not found.");const{error}=await supabase.from("task_checklist_items").update({is_completed:complete}).eq("id",id).eq("wedding_id",wedding.id);if(error)throw new Error(error.message);revalidatePath("/tasks");}
export async function deleteChecklistItem(id:string){const{supabase,wedding}=await getWeddingContext();if(!wedding)redirect("/dashboard");const{error}=await supabase.from("task_checklist_items").delete().eq("id",id).eq("wedding_id",wedding.id);if(error)redirect(`/tasks?error=${encodeURIComponent(error.message)}`);revalidatePath("/tasks");}
export async function addTaskComment(taskId:string,formData:FormData){const{supabase,wedding,user}=await getWeddingContext();if(!wedding)redirect("/dashboard");const{error}=await supabase.from("task_comments").insert({wedding_id:wedding.id,task_id:taskId,user_id:user.id,comment:val(formData,"comment")});if(error)redirect(`/tasks?error=${encodeURIComponent(error.message)}`);revalidatePath("/tasks");}
export async function uploadTaskAttachment(taskId:string,formData:FormData){const file=formData.get("attachment");if(!(file instanceof File)||!file.size)redirect("/tasks?error=Choose a file to upload");const{supabase,wedding,user}=await getWeddingContext();if(!wedding)redirect("/dashboard");if(file.size>10*1024*1024)redirect("/tasks?error=Attachments must be smaller than 10 MB");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${wedding.id}/tasks/${taskId}/${crypto.randomUUID()}-${safe}`;const{error:uploadError}=await supabase.storage.from("wedding-documents").upload(path,file,{contentType:file.type||undefined});if(uploadError)redirect(`/tasks?error=${encodeURIComponent(uploadError.message)}`);const{error}=await supabase.from("documents").insert({wedding_id:wedding.id,task_id:taskId,category:"other",name:file.name,file_path:path,file_name:file.name,mime_type:file.type||null,file_size:file.size,uploaded_by:user.id});if(error)redirect(`/tasks?error=${encodeURIComponent(error.message)}`);revalidatePath("/tasks");revalidatePath("/documents");}
