"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getWeddingContext } from "@/lib/wedding";

const val=(form:FormData,key:string)=>String(form.get(key)||"").trim();const nullable=(form:FormData,key:string)=>val(form,key)||null;
export async function uploadDocument(formData:FormData){const file=formData.get("file");if(!(file instanceof File)||!file.size)redirect("/documents?error=Choose a file to upload");const{supabase,wedding,user}=await getWeddingContext();if(!wedding)redirect("/dashboard");if(file.size>10*1024*1024)redirect("/documents?error=Files must be smaller than 10 MB");const category=val(formData,"category")||"other";const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${wedding.id}/documents/${category}/${crypto.randomUUID()}-${safe}`;const{error:uploadError}=await supabase.storage.from("wedding-documents").upload(path,file,{contentType:file.type||undefined});if(uploadError)redirect(`/documents?error=${encodeURIComponent(uploadError.message)}`);const{error}=await supabase.from("documents").insert({wedding_id:wedding.id,supplier_id:nullable(formData,"supplier_id"),budget_item_id:nullable(formData,"budget_item_id"),task_id:nullable(formData,"task_id"),category,name:val(formData,"name")||file.name,file_path:path,file_name:file.name,mime_type:file.type||null,file_size:file.size,notes:nullable(formData,"notes"),uploaded_by:user.id});if(error){await supabase.storage.from("wedding-documents").remove([path]);redirect(`/documents?error=${encodeURIComponent(error.message)}`)}await supabase.from("activity_log").insert({wedding_id:wedding.id,action:"document_uploaded",entity_type:"document",description:`Document uploaded: ${val(formData,"name")||file.name}`});revalidatePath("/documents");revalidatePath("/tasks");redirect("/documents?message=Document uploaded");}
export async function updateDocument(id:string,formData:FormData){const{supabase,wedding}=await getWeddingContext();if(!wedding)redirect("/dashboard");const{error}=await supabase.from("documents").update({name:val(formData,"name"),category:val(formData,"category")||"other",supplier_id:nullable(formData,"supplier_id"),budget_item_id:nullable(formData,"budget_item_id"),task_id:nullable(formData,"task_id"),notes:nullable(formData,"notes")}).eq("id",id).eq("wedding_id",wedding.id);if(error)redirect(`/documents?error=${encodeURIComponent(error.message)}`);revalidatePath("/documents");redirect("/documents?message=Document updated");}
export async function deleteDocument(id:string,filePath:string){const{supabase,wedding}=await getWeddingContext();if(!wedding)redirect("/dashboard");const{error:storageError}=await supabase.storage.from("wedding-documents").remove([filePath]);if(storageError)redirect(`/documents?error=${encodeURIComponent(storageError.message)}`);const{error}=await supabase.from("documents").delete().eq("id",id).eq("wedding_id",wedding.id);if(error)redirect(`/documents?error=${encodeURIComponent(error.message)}`);revalidatePath("/documents");revalidatePath("/tasks");}
