"use client";

import { DndContext, DragEndEvent, MouseSensor, TouchSensor, useDraggable, useDroppable, useSensor, useSensors } from "@dnd-kit/core";
import { GripVertical, MapPin } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState, useTransition } from "react";
import { toast } from "sonner";
import { quickUpdateTimeline, updateTimelineOrder } from "@/app/(dashboard)/timeline/actions";

export type TimelineRow={id:string;title:string;event_date:string|null;start_time:string|null;end_time:string|null;location:string|null;category:string|null;status:string;sort_order:number;description:string|null;supplier_name:string|null;assigned_label:string|null};
const formatDate=(value:string)=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${value}T12:00:00`));

function TimelineCard({item}:{item:TimelineRow}){const router=useRouter();const[pending,startTransition]=useTransition();const drag=useDraggable({id:item.id});const drop=useDroppable({id:item.id});const style=drag.transform?{transform:`translate3d(0, ${drag.transform.y}px, 0)`,zIndex:60}:undefined;const setRef=(node:HTMLElement|null)=>{drag.setNodeRef(node);drop.setNodeRef(node)};function save(values:{start_time?:string;end_time?:string;status?:string}){startTransition(async()=>{try{await quickUpdateTimeline(item.id,values);router.refresh();toast.success("Timeline updated");}catch(error){toast.error(error instanceof Error?error.message:"Could not update item");}})}return <article ref={setRef} style={style} className={`timeline-row card ${drop.isOver?"timeline-over":""} ${pending?"pending":""}`}><button className="timeline-grip" type="button" aria-label={`Reorder ${item.title}`} {...drag.attributes} {...drag.listeners}><GripVertical/></button><div className="timeline-time"><strong>{item.start_time?.slice(0,5)||"TBC"}</strong><small>{item.end_time?`– ${item.end_time.slice(0,5)}`:""}</small></div><i className={`timeline-dot ${item.status}`}/><div className="timeline-copy"><div><h2>{item.title}</h2><span className={`badge ${item.status==="completed"?"badge-success":item.status==="delayed"?"badge-danger":"badge-info"}`}>{item.status.replaceAll("_"," ")}</span></div><p>{item.description||item.category||"Wedding timeline item"}</p><div className="timeline-meta">{item.location&&<span><MapPin/>{item.location}</span>}{item.supplier_name&&<span>{item.supplier_name}</span>}{item.assigned_label&&<span>{item.assigned_label}</span>}</div></div><div className="timeline-quick"><input type="time" defaultValue={item.start_time?.slice(0,5)||""} aria-label={`Start time for ${item.title}`} onBlur={e=>save({start_time:e.target.value||undefined})}/><input type="time" defaultValue={item.end_time?.slice(0,5)||""} aria-label={`End time for ${item.title}`} onBlur={e=>save({end_time:e.target.value||undefined})}/><select value={item.status} aria-label={`Status for ${item.title}`} onChange={e=>save({status:e.target.value})}><option value="planned">Planned</option><option value="confirmed">Confirmed</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="delayed">Delayed</option><option value="cancelled">Cancelled</option></select></div></article>}

export function TimelineBoard({items}:{items:TimelineRow[]}){const[list,setList]=useState(items);const router=useRouter();const[pending,startTransition]=useTransition();useEffect(()=>setList(items),[items]);const sensors=useSensors(useSensor(MouseSensor,{activationConstraint:{distance:5}}),useSensor(TouchSensor,{activationConstraint:{delay:180,tolerance:8}}));function dragEnd(event:DragEndEvent){const active=String(event.active.id),over=event.over?String(event.over.id):null;if(!over||active===over)return;const oldIndex=list.findIndex(item=>item.id===active),newIndex=list.findIndex(item=>item.id===over);if(oldIndex<0||newIndex<0)return;const next=[...list];const[moved]=next.splice(oldIndex,1);next.splice(newIndex,0,moved);setList(next);startTransition(async()=>{try{await updateTimelineOrder(next.map(item=>item.id));router.refresh();toast.success("Timeline reordered");}catch(error){setList(items);toast.error(error instanceof Error?error.message:"Could not reorder timeline");}})}const groups=list.reduce<Record<string,TimelineRow[]>>((acc,item)=>{const key=item.event_date||"No date";(acc[key]||=[]).push(item);return acc},{});return <DndContext sensors={sensors} onDragEnd={dragEnd}><div className={`timeline-board ${pending?"pending":""}`}>{Object.entries(groups).map(([date,rows])=><section className="timeline-day" key={date}><header><span>{date==="No date"?date:formatDate(date)}</span><small>{rows.length} item{rows.length===1?"":"s"}</small></header><div>{rows.map(item=><TimelineCard item={item} key={item.id}/>)}</div></section>)}</div></DndContext>}
