"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getWeddingContext } from "@/lib/wedding";

const val=(form:FormData,key:string)=>String(form.get(key)||"").trim();
const nullable=(form:FormData,key:string)=>val(form,key)||null;
const amount=(form:FormData,key:string)=>Math.max(0,Number(form.get(key)||0));
const checked=(form:FormData,key:string)=>form.get(key)==="on"||form.get(key)==="true";
function supplierPayload(form:FormData){return{business_name:val(form,"business_name"),category:nullable(form,"category"),status:val(form,"status")||"researching",primary_contact_name:nullable(form,"primary_contact_name"),email:nullable(form,"email"),phone:nullable(form,"phone"),website:nullable(form,"website"),social_url:nullable(form,"social_url"),address:nullable(form,"address"),agreed_cost:amount(form,"agreed_cost"),deposit_amount:amount(form,"deposit_amount"),amount_paid:amount(form,"amount_paid"),next_payment_date:nullable(form,"next_payment_date"),contract_signed:checked(form,"contract_signed"),arrival_time:nullable(form,"arrival_time"),setup_time:nullable(form,"setup_time"),service_start_time:nullable(form,"service_start_time"),finish_time:nullable(form,"finish_time"),requirements:nullable(form,"requirements"),emergency_contact_name:nullable(form,"emergency_contact_name"),emergency_contact_phone:nullable(form,"emergency_contact_phone"),notes:nullable(form,"notes")};}

export async function addSupplier(formData:FormData){const{supabase,wedding}=await getWeddingContext();if(!wedding)redirect("/dashboard");const{data,error}=await supabase.from("suppliers").insert({wedding_id:wedding.id,...supplierPayload(formData)}).select("id").single();if(error)redirect(`/suppliers?error=${encodeURIComponent(error.message)}`);await supabase.from("activity_log").insert({wedding_id:wedding.id,action:"supplier_updated",entity_type:"supplier",entity_id:data.id,description:`Supplier added: ${val(formData,"business_name")}`});revalidatePath("/suppliers");revalidatePath("/budget");redirect("/suppliers?message=Supplier added");}

export async function updateSupplier(id:string,formData:FormData){const{supabase,wedding}=await getWeddingContext();if(!wedding)redirect("/dashboard");const{error}=await supabase.from("suppliers").update(supplierPayload(formData)).eq("id",id).eq("wedding_id",wedding.id);if(error)redirect(`/suppliers?error=${encodeURIComponent(error.message)}`);await supabase.from("activity_log").insert({wedding_id:wedding.id,action:"supplier_updated",entity_type:"supplier",entity_id:id,description:`Supplier updated: ${val(formData,"business_name")}`});revalidatePath("/suppliers");revalidatePath("/budget");revalidatePath("/entertainment");redirect("/suppliers?message=Supplier updated");}

export async function deleteSupplier(id:string){const{supabase,wedding}=await getWeddingContext();if(!wedding)redirect("/dashboard");const{error}=await supabase.from("suppliers").delete().eq("id",id).eq("wedding_id",wedding.id);if(error)redirect(`/suppliers?error=${encodeURIComponent(error.message)}`);revalidatePath("/suppliers");revalidatePath("/budget");revalidatePath("/entertainment");}

export async function uploadSupplierDocument(id:string,formData:FormData){const file=formData.get("attachment");if(!(file instanceof File)||!file.size)redirect("/suppliers?error=Choose a file to upload");const{supabase,wedding,user}=await getWeddingContext();if(!wedding)redirect("/dashboard");if(file.size>10*1024*1024)redirect("/suppliers?error=Attachments must be smaller than 10 MB");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${wedding.id}/suppliers/${id}/${crypto.randomUUID()}-${safe}`;const{error:uploadError}=await supabase.storage.from("wedding-documents").upload(path,file,{contentType:file.type||undefined});if(uploadError)redirect(`/suppliers?error=${encodeURIComponent(uploadError.message)}`);const category=val(formData,"document_category")||"contract";const{error}=await supabase.from("documents").insert({wedding_id:wedding.id,supplier_id:id,category,name:file.name,file_path:path,file_name:file.name,mime_type:file.type||null,file_size:file.size,uploaded_by:user.id});if(error)redirect(`/suppliers?error=${encodeURIComponent(error.message)}`);revalidatePath("/suppliers");redirect("/suppliers?message=Document attached");}
